<a href="https://colab.research.google.com/github/hieu-le-2412/ai-course/blob/master/Sonar_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this homework, we will build a simple neural network model to identify whether rocks (0) or mock-mines (1) using the Sonar dataset. This is a binary classification problem.

The dataset contains two csv files: sonar_train.csv (160x61) and sonar_test.csv (58x61). There are 60 input values and a single output value and the input values are standardized before being used in the network. The dataset is uploaded in Github and the skeleton code below provides the function to read these dataset.

Your task is to build a baseline neural network model has two hidden layers: the first with 60 units and the second with 30. Stochastic gradient descent is used to train the model with a relatively low learning rate (=0.01) and momentum (=0.8). The binary cross entropy loss is used.

Below is the skeleton for the homework:

In [1]:
import numpy as np
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
import urllib.request as request
import csv

Using TensorFlow backend.


In [0]:
def read_data(url):
  dataframe = read_csv(url)
  dataset = dataframe.values
  # split into input (X) and output (Y) variables
  X = dataset[:,0:60].astype(float)
  Y = dataset[:,60]
  return X, Y

In [0]:
# load dataset
url_train = 'https://raw.githubusercontent.com/rangnguyen/deeplearning/master/hw1/sonar_train.csv'
url_test = 'https://raw.githubusercontent.com/rangnguyen/deeplearning/master/hw1/sonar_test.csv'

X_train, Y_train = read_data(url_train)
X_test, Y_test = read_data(url_test)


In [9]:
# Check dataset
X_train.shape

(159, 60)

In [10]:
Y_train.shape

(159,)

In [7]:
X_test

array([[0.0036, 0.0078, 0.0092, ..., 0.0049, 0.0024, 0.0016],
       [0.0208, 0.0186, 0.0131, ..., 0.0019, 0.0049, 0.0023],
       [0.0139, 0.0222, 0.0089, ..., 0.0059, 0.0039, 0.0048],
       ...,
       [0.0522, 0.0437, 0.018 , ..., 0.0138, 0.0077, 0.0031],
       [0.0303, 0.0353, 0.049 , ..., 0.0079, 0.0036, 0.0048],
       [0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115]])

In [8]:
Y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [0]:
# baseline
def create_model():  
  model = Sequential()
  # YOUR CODE HERE
  model.add(Dense(units=60, input_shape=(60,)))
  model.add(Dense(units=30, activation='relu'))
  model.add(Dense(units=1, activation='sigmoid'))
  sgd = SGD(lr=0.01, momentum=0.8)
  model.compile(optimizer=sgd, loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [25]:
model = create_model()
model.fit(X_train, Y_train, epochs=1000)


Epoch 1/1000
159/159 [==============================] - 0s 3ms/step - loss: 0.6829 - acc: 0.5723
Epoch 2/1000
159/159 [==============================] - 0s 94us/step - loss: 0.6691 - acc: 0.5723
Epoch 3/1000
159/159 [==============================] - 0s 93us/step - loss: 0.6590 - acc: 0.6226
Epoch 4/1000
159/159 [==============================] - 0s 99us/step - loss: 0.6454 - acc: 0.6226
Epoch 5/1000
159/159 [==============================] - 0s 77us/step - loss: 0.6352 - acc: 0.6226
Epoch 6/1000
159/159 [==============================] - 0s 73us/step - loss: 0.6245 - acc: 0.6352
Epoch 7/1000
159/159 [==============================] - 0s 70us/step - loss: 0.6171 - acc: 0.6289
Epoch 8/1000
159/159 [==============================] - 0s 81us/step - loss: 0.6078 - acc: 0.6478
Epoch 9/1000
159/159 [==============================] - 0s 64us/step - loss: 0.6015 - acc: 0.6541
Epoch 10/1000
159/159 [==============================] - 0s 75us/step - loss: 0.5926 - acc: 0.6792
Epoch 11/1000
159/15

In [26]:
score, acc = model.evaluate(X_test, Y_test, batch_size=160)

print("Test accuracy: %.2f%%" % (acc))

57/57 [==============================] - 0s 2ms/step
Test accuracy: 0.79%


In [27]:
# Predict
pred = model.predict(X_test)
pred

array([[6.2585473e-03],
       [3.0502975e-03],
       [1.0498944e-01],
       [6.5014035e-02],
       [9.9962354e-01],
       [9.9992412e-01],
       [9.9997044e-01],
       [9.9987984e-01],
       [9.9995327e-01],
       [9.7410971e-01],
       [9.9999970e-01],
       [9.9999982e-01],
       [1.0000000e+00],
       [9.9999988e-01],
       [9.4922036e-02],
       [3.6835641e-02],
       [6.8839818e-02],
       [8.9181215e-02],
       [1.7691499e-01],
       [0.0000000e+00],
       [4.2901039e-03],
       [3.5695434e-03],
       [9.9963486e-01],
       [1.1161864e-01],
       [2.8917193e-04],
       [7.1495771e-05],
       [9.5695490e-01],
       [9.3528831e-01],
       [9.7927153e-01],
       [1.0000000e+00],
       [1.0000000e+00],
       [9.9999994e-01],
       [1.0000000e+00],
       [1.0000000e+00],
       [9.9999988e-01],
       [9.9999928e-01],
       [9.9997926e-01],
       [9.9964106e-01],
       [8.9501476e-01],
       [9.9314320e-01],
       [8.3835149e-01],
       [9.825418